import Head from 'next/head';
import { useRouter } from 'next/router';
import { ChevronLeftIcon, ChevronRightIcon, TrendingDownIcon, TrendingUpIcon } from '@heroicons/react/solid';

export default function Home() {
  const router = useRouter();
  return (
    <div className=''>
      <Head>
        <title>Budgerz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='flex items-center justify-between mb-10'>
        <h1 className='text-xl font-bold'>Home</h1>
        <div className='flex space-x-4 items-center text-lg'>
          <ChevronLeftIcon className='w-7 cursor-pointer text-indigo-500' />
          <span>Mei 2022</span>
          <ChevronRightIcon className='w-7 cursor-pointer text-indigo-500' />
        </div>
      </header>
      <main>
        <div className='mb-10'>
          <div className='mb-5 flex flex-col sm:flex-row sm:space-x-10 space-y-5 sm:space-y-0 text-white'>
            <div className='bg-indigo-500 rounded-lg p-5 flex-1 cursor-pointer flex justify-between items-center'>
              <div className='space-y-3'>
                <h3 className='text-lg'>Mijn inkomsten</h3>
                <p className='font-bold text-xl'>&euro; 2.000,00</p>
              </div>
              <TrendingUpIcon className='w-10' />
            </div>
            <div className='bg-pink-500 rounded-lg p-5 flex-1 cursor-pointer flex justify-between items-center'>
              <div className='space-y-3'>
                <h3 className='text-lg'>Mijn uitgaven</h3>
                <p className='font-bold text-xl'>&euro; 1.500,00</p>
              </div>
              <TrendingDownIcon className='w-10' />
            </div>
          </div>
          <div className='flex items-center justify-between sm:justify-end sm: space-x-5 font-bold text-lg'>
            <p>Resterend bedrag</p>
            <p>&euro; 500,00 </p>
          </div>
        </div>
        <div>
          <div className='text-center bg-gray-100 rounded-lg p-3 border border-gray-400 font-bold'>
            Vaste Lasten
          </div>
          <div></div>
        </div>
      </main>
    </div>
  );
}
