import Head from 'next/head';
import { useRouter } from 'next/router';
import {
  ChevronLeftIcon,
  ChevronRightIcon,
  EmojiHappyIcon,
  TrendingDownIcon,
  TrendingUpIcon,
} from '@heroicons/react/solid';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { Doughnut } from 'react-chartjs-2';

export default function Home() {
  const router = useRouter();
  return (
    <div className=''>
      <Head>
        <title>Budgerz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='flex items-center justify-between mb-8'>
        <h1 className='text-xl font-bold'>Home</h1>
        <div className='flex space-x-4 items-center text-lg'>
          <ChevronLeftIcon className='w-8 cursor-pointer text-blue-500' />
          <span>Mei 2022</span>
          <ChevronRightIcon className='w-8 cursor-pointer text-blue-500' />
        </div>
      </header>
      <main>
        <div className='mb-8'>
          <div className='mb-5 flex flex-col sm:flex-row sm:space-x-10 space-y-5 sm:space-y-0 text-white'>
            <div className='bg-blue-500 rounded-lg p-5 flex-1 cursor-pointer flex justify-between items-center'>
              <div className='space-y-3'>
                <h3 className='text-lg'>Totaal inkomsten</h3>
                <p className='font-bold text-xl'>&euro; 2.000,00</p>
              </div>
              <TrendingUpIcon className='w-10' />
            </div>
            <div className='bg-red-500 rounded-lg p-5 flex-1 cursor-pointer flex justify-between items-center'>
              <div className='space-y-3'>
                <h3 className='text-lg'>Totaal uitgaven</h3>
                <p className='font-bold text-xl'>&euro; 1.500,00</p>
              </div>
              <TrendingDownIcon className='w-10' />
            </div>
            <div className='bg-green-500 rounded-lg p-5 flex-1 cursor-pointer flex justify-between items-center'>
              <div className='space-y-3'>
                <h3 className='text-lg'>Resterend bedrag</h3>
                <p className='font-bold text-xl'>&euro; 500,00</p>
              </div>
              <EmojiHappyIcon className='w-10' />
            </div>
          </div>
        </div>
        <div>
          <Doughnut data={data} />
        </div>
      </main>
    </div>
  );
}

ChartJS.register(ArcElement, Tooltip, Legend);

export const data = {
  labels: ['Inkomsten', 'Uitgaven', 'Resterend'],
  datasets: [
    {
      label: 'Budget',
      data: [2000, 1500, 500],
      backgroundColor: ['#bfdbfe', '#fecaca', '#bbf7d0'],
      borderColor: ['#3b82f6', '#ef4444', '#22c55e'],
      borderWidth: 1,
    },
  ],
};
