import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Instellingen() {
  const router = useRouter();
  return (
    <div className=''>
      <Head>
        <title>Budgerz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div
        className='bg-gradient-to-r from-blue-500  to-red-500 text-white rounded-lg font-bold py-3 text-center cursor-pointer w-fit px-4'
        onClick={() => router.push('/inloggen')}
      >
        Log in page
      </div>
    </div>
  );
}
