import React from 'react'
import Head from 'next/head';

export default function Instellingen() {
  return (
    <div className=' p-5'>
      <Head>
        <title>Budgerz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='space-y-6'>
          Instellingen
      </main>
    </div>
  );
}
